blank_issues_enabled: true
contact_links:
  - name: Support questions 💬
    url: https://github.com/orgs/pos-zone/discussions
    about: Find announcements, discussions, recipes and much more in the Turath Discussions.
  - name: Propose a change to Tūrath 📝
    url: https://github.com/pos-zone/rfcs/
    about: Would you like to propose a change to Turath? RFC is what you are looking for!
